apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-7p2n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-7p2n
    app.kubernetes.io/part-of: test-app-vrgm
  name: maven-hello-world-7p2ng5tw
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: maven-hello-world-7p2n
    weight: null
status: {}
