apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-adty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-adty
    app.kubernetes.io/part-of: test-app-vrgm
  name: nodejs-no-dockerfile-adty
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-adty
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-adty
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-inxo-tenant/test-app-vrgm/nodejs-no-dockerfile-adty@sha256:ea7a52317e3980983c43eeddb38d3fad810db19a5c0448716e3a223f0ac7433f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
